import * as vscode from 'vscode';
import { FocusEntry } from '../models/focusEntry';
import { TreeOperations } from './treeOperations';
import { buildContext, TokenBudgetResult } from './tokenBudget';
import { configuration } from './configurationManager';

/**
 * Send Focus Space entries to Copilot Chat.
 *
 * Resolves target entries, builds token-budgeted context, copies formatted
 * markdown to clipboard, and attempts to open Copilot Chat.
 *
 * @param entries - Top-level entries to process (files, sections, or mixed)
 * @param token - Cancellation token for progress support
 */
export async function sendToCopilot(
    entries: FocusEntry[],
    token?: vscode.CancellationToken,
): Promise<void> {
    // Flatten to file-only entries
    const fileEntries = TreeOperations.flatten(entries)
        .filter((e: FocusEntry) => e.type === 'file');

    if (fileEntries.length === 0) {
        vscode.window.showInformationMessage('No files to send to Copilot Chat.');
        return;
    }

    // Build context with token budget
    const budget = configuration.copilotTokenBudget;
    const result: TokenBudgetResult = await buildContext(fileEntries, budget, token);

    if (token?.isCancellationRequested) {
        return;
    }

    if (result.includedFiles.length === 0) {
        vscode.window.showWarningMessage(
            'No files could be included. All were binary, missing, or exceeded size limits.'
        );
        return;
    }

    // Format markdown output
    const markdown = formatMarkdown(result);

    // Copy to clipboard as fallback
    await vscode.env.clipboard.writeText(markdown);

    // Attempt to open Copilot Chat with content pre-filled in input
    let chatOpened = false;
    try {
        await vscode.commands.executeCommand('workbench.action.chat.open', {
            query: markdown,
            isPartialQuery: true,
        });
        chatOpened = true;
    } catch {
        // Copilot Chat may not be available — fall back to clipboard-only
        try {
            await vscode.commands.executeCommand('workbench.action.chat.open');
            chatOpened = true;
        } catch {
            // No chat available at all
        }
    }

    // Build summary message
    const parts: string[] = [
        `${result.includedFiles.length} files sent to Copilot Chat (${result.budgetUsedPercent}% of token budget).`,
    ];
    if (result.excludedCount > 0) {
        parts.push(`${result.excludedCount} excluded (budget/size)`);
    }
    if (result.skippedBinary > 0) {
        parts.push(`${result.skippedBinary} binary skipped`);
    }
    if (result.skippedMissing > 0) {
        parts.push(`${result.skippedMissing} missing skipped`);
    }

    if (!chatOpened) {
        parts[0] = `${result.includedFiles.length} files copied to clipboard (${result.budgetUsedPercent}% of token budget).`;
        vscode.window.showInformationMessage(
            parts.length > 1 ? `${parts[0]} ${parts.slice(1).join(', ')}.` : `${parts[0]} Paste into Copilot Chat.`
        );
    } else {
        vscode.window.showInformationMessage(
            parts.length > 1 ? `${parts[0]} ${parts.slice(1).join(', ')}.` : `${parts[0]} Press Enter to send.`
        );
    }
}

/**
 * Format a TokenBudgetResult into markdown suitable for Copilot Chat.
 */
function formatMarkdown(result: TokenBudgetResult): string {
    const lines: string[] = [];

    lines.push(`# Focus Space Context (${result.includedFiles.length} files)\n`);
    lines.push(`**Estimated tokens:** ~${result.totalTokensEstimated.toLocaleString()}\n`);

    for (const file of result.includedFiles) {
        lines.push(`## ${file.relativePath}`);
        if (file.wasTruncated) {
            lines.push('*Content truncated to fit budget.*\n');
        }
        const lang = file.language || '';
        lines.push('```' + lang);
        lines.push(file.content);
        lines.push('```\n');
    }

    if (result.excludedCount > 0) {
        lines.push(`\n> **Note:** ${result.excludedCount} file(s) were excluded due to token budget or size limits.\n`);
    }

    lines.push('---');
    lines.push('*Generated by Focus Space extension*');

    return lines.join('\n');
}