name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint
        continue-on-error: true

      - name: Compile TypeScript
        run: npm run compile

      - name: Setup test environment (Linux)
        if: runner.os == 'Linux'
        run: |
          # Create test directories
          sudo mkdir -p /test/{folder,src,empty-folder,project,my-project,auto-convert-folder,convert-folder,reveal-folder}
          sudo mkdir -p /project/src
          # Create test files
          sudo touch /test/{file.ts,renamed.ts,external-file.ts,external-to-section.ts,existing.ts,valid.ts}
          sudo mkdir -p /test/external-folder && sudo touch /test/external-folder/index.ts
          sudo touch /test/folder/{file1.ts,file2.ts}
          sudo touch /test/src/main.ts
          sudo touch /test/project/app.ts
          sudo touch /test/my-project/index.ts
          sudo touch /project/src/component.ts
          # Make directories writable for tests
          sudo chmod -R 755 /test /project
          echo "Test environment setup completed"

      - name: Run tests
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            xvfb-run -a npm test
          else
            npm test
          fi

      - name: Package extension (test build)
        run: |
          npx @vscode/vsce package --out test-build.vsix

      - name: Upload test package
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == 18
        with:
          name: test-extension-package
          path: test-build.vsix